### ISSUE TITLE
Not compatible with webtrees 2.0.12?

### ISSUE THREAD

**Issue by HRN65** [magicsunday/webtrees-fan-chart#59]
Testing the fan-chart on my local test site running webtrees 2.0.12, the chart is not loading.
No error messages.

**Comment by mpwt** [comment]
It still works on my site that I just updated manually.

**Comment by HRN65** [comment]
On local test site I still get a code hung, but upgrading my live site to 2.0.12, the fan chart works fine!

**Comment by magicsunday** [comment]
Are there errors in the browser console (F12)?

**Comment by HRN65** [comment]
No errors in console.

At first config form is visible, but chart is not rendering, only a spinning wheel, followed by a pop up message saying page does not load, and the choices wait/cancel. Canceling results in white page saying There is a problem with this page, Error: RESULT_CODE_HUNG

Local test site running on WAMP Server php 7.4.9
Fan chart works fine on my live site just upgraded to php 7.4.16

**Comment by hartenthaler** [comment]
I have the same problem for some weeks when using Edge. I do not have this problem when using Chrome. Using Edge, I can open the menu, but cannot click at any of the controls, the wheel is spinning and never stops.
![Screenshot (218)_LI](https://user-images.githubusercontent.com/6324175/111087147-2fa93c80-8520-11eb-8290-2b851e16f2d9.jpg)

**Comment by hartenthaler** [comment]
I can open https://ann-britt.se/tree/Ann-Britt%27s%20Anor/webtrees-fan-chart/I4709 without any problems using Edge. Strange. It seems to depend on a combination of Browser/something else.

**Comment by magicsunday** [comment]
Should be fixed with the latest release. Webtrees removed some of the used core methods.

**Comment by hartenthaler** [comment]
The problem does still exist and is not solved. Sorry.

**Comment by magicsunday** [comment]
Hard to guess what the problem may be. I tested it with Edge 89.0.774.54, webtrees 2.0.13 and version 2.1.6 of the fanchart module. No issues. Do you have an public accessible testing site?

**Comment by hartenthaler** [comment]
I'm using Edge 89.0.774.54, webtrees 2.0.13, and version 2.1.6 of the fanchart module, too. Tested it with https://ahnen.hartenthaler.eu/tree/ahnen/webtrees-fan-chart/I318 from my laptop: error (endless spinning wheel) still exists. Tested from another PC with the same version of Edge: no problem. Strange. The only thing which I can see: at my laptop when opening my own webtrees, there is no entry in the field "Generations" (see my previous screenshot). I can open with my Edge browser on my laptop other webtrees fancharts without problems. I can open my webtrees fanchart using a Edge browser from another PC without problems. Maybe I should deinstall and reinstall my Edge on the laptop.

**Comment by hartenthaler** [comment]
@HRN65 Is your problem solved or still existing?

**Comment by HRN65** [comment]
Just updated to version 2.1.6 and tested local site (webtrees 2.0.13 on WAMP Server php 7.4.9) and live site (webtrees 2.0.13/php 7.4.16) 
On live site http://visitusinmaputo.com/webtree the fan chart loads nicely in Chrome 89.0.4389.90, Firefox 86.0.1 and Edge 89.0.774.54. Also works on iPad and Android phone.

On local test site, the fan chart does not load in Edge, and there is no entry in the field "Generations". 
Firefox and Chrome are OK.

**Comment by magicsunday** [comment]
Does it help if your remove the entry "webtrees-fan-chart" from the local storage?

![grafik](https://user-images.githubusercontent.com/564393/111428110-5bcae600-86f7-11eb-8bc1-5a34e4d2bad8.png)

**Comment by hartenthaler** [comment]
Where can I find this local storage setting?
Yes, the Generations selectbox is empty.

**Comment by HRN65** [comment]
@magicsunday 
Yes, the generations selectionbox is empty when entering the page, and deleting the entry "webtrees-fan-chart" does not help.

@hartenthaler 
Press F12 and choose Application -> Storage -> Local Storage, and expand.

![storage](https://user-images.githubusercontent.com/55854079/111653019-d84cea00-8807-11eb-9296-07e7eb3acb92.png)

**Comment by hartenthaler** [comment]
Thank you! What I found:
```
{fanDegree: "235", generations: "21", hideEmptySegments: true, showColorGradients: true,…}
fanDegree: "235"
fontScale: "100"
generations: "21"
hideEmptySegments: true
innerArcs: "4"
showColorGradients: true
showEmptyBoxes: false
showMoreOptions: true
```
Deleting the entry "webtrees-fan-chart" solved the problem! Now it is working perfect again. What was the reason that generations was set to 21?

**Comment by magicsunday** [comment]
Very strange. I will have to investigate it.

**Comment by magicsunday** [comment]
I dont know whats happening here, but I can reproduce it if I manually change the number of generations to a value out of scope. But I was not able to force it programmatically.

**Comment by hartenthaler** [comment]
Since March this problem never showed up again. Maybe you can close this issue.
